# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_tracking', '0001_initial'),
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_for_purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_purchase_date', models.DateField()),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('purchase_status', models.IntegerField(choices=[('0', 'Pending'), ('1', 'Approve'), ('2', 'Items Ordered'), ('3', 'Items Puchased'), ('4', 'Items Delivered')], default='0')),
                ('amount', models.IntegerField(default='0')),
                ('purchase_date', models.DateField()),
                ('registrar_approve_tag', models.IntegerField(choices=[('0', 'Pending'), ('1', 'Approve')], default='0')),
                ('accounts_approve_tag', models.IntegerField(choices=[('0', 'Pending'), ('1', 'Approve')], default='0')),
                ('purchase_type', models.IntegerField(choices=[('0', 'Amount < 25000'), ('1', '25000<Amount<250000'), ('2', '250000<Amount < 2500000'), ('3', 'Amount>2500000')], default='0')),
                ('purpose', models.CharField(max_length=200)),
                ('invoice', models.FileField(upload_to='')),
                ('nature_of_item1', models.IntegerField(choices=[('0', 'Non-consumable'), ('1', 'Consumable')], default='0')),
                ('nature_of_item2', models.IntegerField(choices=[('0', 'Equipment'), ('1', 'Machinery'), ('2', 'Furniture'), ('3', 'Fixture')], default='0')),
                ('item_name', models.CharField(max_length=100)),
                ('expected_cost', models.IntegerField(default='0')),
                ('quantity', models.IntegerField(default='0')),
                ('budgetary_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bud_head', to='globals.ExtraInfo')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Designation')),
                ('indentor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indentor_name', to='globals.ExtraInfo')),
                ('inspecting_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecting_authority', to='globals.ExtraInfo')),
                ('purchase_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_commitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_mem1', models.IntegerField(choices=[('0', 'Pending'), ('1', 'Approve')], default='0')),
                ('approve_mem2', models.IntegerField(choices=[('0', 'Pending'), ('1', 'Approve')], default='0')),
                ('approve_mem3', models.IntegerField(choices=[('0', 'Pending'), ('1', 'Approve')], default='0')),
                ('local_comm_mem1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_comm_mem1', to='globals.ExtraInfo')),
                ('local_comm_mem2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_comm_mem2', to='globals.ExtraInfo')),
                ('local_comm_mem3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_comm_mem3', to='globals.ExtraInfo')),
            ],
        ),
        migrations.CreateModel(
            name='quotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation1', models.FileField(upload_to='')),
                ('quotation2', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='registrar_create_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='registrar_director_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[('0', 'unseen'), ('1', 'seen')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='registrar_establishment_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('post', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('0', 'unseen'), ('1', 'seen')], default=0)),
                ('approval', models.IntegerField(choices=[('0', 'reject'), ('1', 'accept')], default=0)),
                ('section_name', models.CharField(max_length=50)),
                ('section_type', models.CharField(max_length=20)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_tracking.Tracking')),
            ],
        ),
        migrations.CreateModel(
            name='registrar_finance_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[('0', 'unseen'), ('1', 'seen')], default=0)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='registrar_general_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField(choices=[('0', 'unseen'), ('1', 'seen')], default=0)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='registrar_purchase_sales_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('member1', models.CharField(max_length=50)),
                ('member2', models.CharField(max_length=50)),
                ('member3', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[('0', 'unseen'), ('1', 'seen')], default=0)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default='0')),
                ('item_type', models.IntegerField(choices=[('0', 'Non-consumable'), ('1', 'Consumable')], default='0')),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_address', models.CharField(max_length=200)),
            ],
        ),
    ]
