# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrar_create_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
