# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-15 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar_establishment_section',
            name='person_mail_id',
            field=models.CharField(default='xyz', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrar_finance_section',
            name='status',
            field=models.IntegerField(choices=[('0', 'unseen'), ('1', 'seen')]),
        ),
    ]
