# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_tracking', '0001_initial'),
        ('office_module', '0002_apply_for_purchase_purchase_commitee_quotations_registrar_create_doc_stock_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('0', 'unseen'), ('1', 'seen')], default=0)),
                ('approval', models.IntegerField(choices=[('0', 'reject'), ('1', 'accept')], default=0)),
                ('section_name', models.CharField(max_length=50)),
                ('section_type', models.CharField(max_length=20)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_tracking.Tracking')),
            ],
        ),
    ]
