# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_module', '0002_auto_20180415_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_director_section',
            name='status',
            field=models.CharField(choices=[('0', 'unseen'), ('1', 'seen')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='registrar_general_section',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_module.registrar_create_doc'),
        ),
    ]
