# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_module', '0003_registrar_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrar_create_doc',
            name='file',
        ),
    ]
