# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office_module', '0004_remove_registrar_create_doc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar_create_doc',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
